stages:
- stage: continuous_integration
  displayName: Continuous Integration
  jobs:
  - job: build
    displayName: Build
    steps:
    - script: dotnet build
      displayName: Build .NET Core Project
    - script: dotnet publish --configuration Release --output out --self-contained --runtime win-x64 /p:PublishSingleFile=true
      displayName: Publish .NET Core Project
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: out
        ArtifactName: build
  - job: test
    displayName: Test
    steps:
    - script: dotnet test
      displayName: Test .NET Core Project